### ISSUE TITLE
LaserIO Redstone interaction with Modular Routers in Direwolf20 1.18 v1.8.0 Modpack

### ISSUE THREAD

**Issue by sub90** [Direwolf20-MC/LaserIO#111]
### LaserIO version

1.3.2

### Minecraft Version

1.18

### Modpack & Version

Direwolf 20 1.18 - 1.8.0

### Do you have optifine installed?

No

### Describe the issue

When using LaserIO redstone to fire a Modular router, an undesirable behavior occurs. The redstone passed through LaserIO is is affecting modular routers adjacent to the intended router. 

### Steps to reproduce

1. Three modular routers are configured as placers and placed adjacent to each other in a horizontal row.
2. All Three routers are set to action on High redstone signal in pulse mode.
3. Laser IO linked to and configured to send redstone signal to only the center Router.
4. Redstone signal is sent to LaserIO via button.
5. All three routers receive the signal. (why?)
6. All three Routers place their blocks in the world. 

FYI - This behavior does not occur if using Redstone Transmitters.

### Expected behaviour

One would expect LaserIO to only affect the blocks for which it is directly attached.,

**Comment by Direwolf20-MC** [comment]
Is the redstone output card set to 'Strong signal'? If so that is intended behavior -- I can't reproduce this bug when the output signal is set to 'weak' which is the default. 

![image](https://user-images.githubusercontent.com/39863894/182240547-d0fbe726-768d-4b3b-b0be-75724051f8d3.png)
![image](https://user-images.githubusercontent.com/39863894/182240586-c5bdec52-2ec8-4702-8193-57bf245d46f2.png)

**Comment by sub90** [comment]
Yes it is/was set to high. I was unaware of this difference between these modes. Is this documented anywhere? Is it a LaserIO behavior or a minecraft behavior?

Thanks! I'll try it on our world.
