### ISSUE TITLE
Cards get voided from the card holder when switching gamemodes

### ISSUE THREAD

**Issue by Gobgob30** [Direwolf20-MC/LaserIO#138]
### LaserIO version

1.4.3

### Minecraft Version

1.18.2

### Forge Version

40.1.79

### Modpack & Version

ATM6 1.0.7

### Do you have optifine installed?

No

### Describe the issue

Changing gamemodes causes the card holder to void its contents

### Steps to reproduce

Have a card holder in inventory _**NOT HOTBAR**_
Change game mode, tried with both commands and the selector same happens
Cards are voided.

### Expected behaviour

Nothing to change with the card holder.

### Screenshots

![image](https://user-images.githubusercontent.com/97519613/192124237-c4394b4d-0fa5-4fae-a4b9-1e9eb9c54e8d.png)
![image](https://user-images.githubusercontent.com/97519613/192124242-d5fb3686-356a-4664-8556-4e42cfa9ad91.png)
![image](https://user-images.githubusercontent.com/97519613/192124246-071e4e8f-c3bd-4717-b079-c4a41aac6235.png)

**Comment by MichaelHillcox** [comment]
Oh, this is an ancient forge bug, I think it's still around in 1.19.

The best solution here is to move the bag over to World Storage or to not use a forge cap for the item storage and instead use your own NBT locations for the items which you then expose via the forge cap in real time if you want other mods to continue to use it.

**Comment by Direwolf20-MC** [comment]
I've tried to reproduce this bug - i think it only happens if you got the card holder on an older version of the mod and then updated to a newer version.  Card holders from newer versions don't SEEM to have this problem. I just tested myself, and can't reproduce.  

Give yourself a new card holder, and then see if you can reproduce :). If yes, i'll re-open the bug.
