### ISSUE TITLE
Unexpected behavior with Counting Filter

### ISSUE THREAD

**Issue by kalutro** [Direwolf20-MC/LaserIO#170]
### LaserIO version

1.4.5

### Minecraft Version

1.18.2

### Forge Version

40.2.1

### Modpack & Version

Skyopolis 5 v4.1

### Do you have optifine installed?

No

### Describe the issue

I am getting an unexpected result when using a counting filter. As shown in the image, the filter is set to multiple items. My issue is that if cobblestone is ever above it's threshold, it will be extracted over other items. All priorities are set to 0, but even if I change the cobblestone's priority (higher or lower) the behavior is the same.

### Steps to reproduce

I am using Storage Drawers to hold the items. The extract node is connected to the Drawer Controller. The insert nodes are connected to Chutes.  Cobblestone is being fed into the drawers via a Cobble Gen that generates 1 cobble every 10 ticks. As you can see in the image, extraction is set to 10 ticks. If I reduce it to 9, the issue resolves. If I remove the cobble from the filter, the issue resolves. Why is the cobble being extracted first? The world may never know.

### Expected behaviour

I would expect the items to be extracted in the order they appear in the filter.

### Screenshots

![laseriocobble](https://user-images.githubusercontent.com/69569507/223070258-a19d6c4f-7e66-46da-9808-8c62631170fb.png)

### Additional information

It doesn't matter at what value I set the cobble, it always goes first. Yes, the quantity of the other items is over their respective thresholds.

**Comment by IONayrus** [comment]
As far as i know, the Card checks the target inventory slot by slot per operation. If your first slot always has to much cobble it will choose to extract that - which counts as the operation done. If you set the extract rate to 9 it will always have a 1 tick window where the first slots cobble amount is ok, so it'll have a look at other slots. The Insert Priority doesnt matter since the extract operation is the cause.

When you have a steady supply of items like this, you need to make an extra Extract Card for that specific item and use a Node Overclocker on the Node so that both cards can operate at the same time. This is not a bug but intended feature.

Alternatively you can try to setup your drawers in a different way/link them in a different way so that the cobble drawer is not treated as the first slot. But that is determined by the Drawer Controller and the reason why cobble is extracted first. Considering the flow of Skyblock packs i guess you set that drawer up first right?

**Comment by kalutro** [comment]
I am going to blame my lack of sleep while diagnosing on this one.

After reading your reply and re-watching Dire's mod spotlight video, I believe the issue is resolved. Also, I forgot the part where the two insert cards are in different nodes. I apologize.

I assume because the cobble node is closer to the extract node, it gets checked first. It all makes sense now!
