### ISSUE TITLE
crash with shaders

### ISSUE THREAD

**Issue by Vadewolf** [Direwolf20-MC/LaserIO#190]
### LaserIO version

1.6.4

### Minecraft Version

1.20.1

### Forge Version

47.0.19

### Modpack & Version

custom modpack

### Do you have optifine installed?

I have other rendering based mods installed

### Describe the issue

launch my modpack and with the latest update to Laser IO it crashes due to a shadow render bug

### Steps to reproduce

1 update to 1.6.4 laser io

2 open MC

3 Crash
[crash-2023-07-13_09.02.02-client.txt](https://github.com/Direwolf20-MC/LaserIO/files/12050740/crash-2023-07-13_09.02.02-client.txt)
[crash-2023-07-13_09.03.06-client.txt](https://github.com/Direwolf20-MC/LaserIO/files/12050741/crash-2023-07-13_09.03.06-client.txt)
[crash-2023-07-13_09.17.03-client.txt](https://github.com/Direwolf20-MC/LaserIO/files/12050742/crash-2023-07-13_09.17.03-client.txt)

hope this helps

### Expected behaviour

no crash

**Comment by Vadewolf** [comment]
basically for render mods i just have rubidium and oculus with shaders which works with laser IO b4 the 1.6.4 update but on that update i get a shadow render crash cause of laser io and oculus (tho if u read the logs they say iris)

**Comment by Direwolf20-MC** [comment]
I don’t think this is LaserIO related as I don’t see it mentioned in the crash reports at all. I’d recommend posting over at iris or rubidium’s GitHub :). Let me know if it turns out to be LaserIO after all though!

**Comment by Vadewolf** [comment]
it is with laser io tho and that specfic update because if i downgrade to the one just before it then it works with no issue

**Comment by Direwolf20-MC** [comment]
Are you changing forge versions at all? The problem is that LaserIO isn't mentioned at all in the stacktrace. Its possible that something LaserIO is doing is causing an issue in Iris to become apparent? I'd still vote for you to make a report over there, and ask them to hit me up here if they think its something I'm doing :).

**Comment by Vadewolf** [comment]
will do and ill test the forge version but ik when i update Laser IO i get the crash but that was b4 seeing the new forge version

**Comment by Vadewolf** [comment]
[crash-2023-07-14_16.06.34-client.txt](https://github.com/Direwolf20-MC/LaserIO/files/12053931/crash-2023-07-14_16.06.34-client.txt)

latest crash and this is after changing forge and laser io

**Comment by Vadewolf** [comment]
something between 1.6.4 laser io and iris/oculus doesnt like each other but version 1.6.3 works fine

**Comment by Direwolf20-MC** [comment]
Sorry it still looks to be on the iris side. Have you reported it there? Can you link the report you made over there for me?

**Comment by Vadewolf** [comment]
i havent made one yet cause i havent been able to find the right github

**Comment by Vadewolf** [comment]
tho if its on iris side then y wouldnt it do the exact same crash on 1.6.3?

**Comment by Direwolf20-MC** [comment]
I don’t have a good answer for that. Best I can tell you is there’s no mention of LaserIO anywhere in the crash log.

**Comment by Vadewolf** [comment]
its just odd as heck that 1.6.3 laser io works but 1.6.4 crashes instantly

**Comment by Vadewolf** [comment]
@Direwolf20-MC heres basically someone else making the report but the exact same issue as mine shown above

https://github.com/Asek3/Oculus/issues/413

**Comment by Direwolf20-MC** [comment]
We’ll let me put it this way :). At this point I can’t guarantee I’m not doing something to cause this - but since the stack trace doesn’t have my mod listed in it there’s no way for me to know what or where the problem is. 

It *sounds* like an issue with their mod being brought out when my mod is present. We really need them to look at the error and determine if it’s me or them and then have them tell me if it’s me and why :). 

There’s really nothing else I can do right now. But if they tell you it’s something on my end please point me to it because I have no idea where to look based on the stack traces provided

**Comment by Vadewolf** [comment]
one thing i can say is look into any changes that were made specfic in the 1.6.4 version since ik thats when the crash happens for me

**Comment by Vadewolf** [comment]
ok so found out its 100% patchouli thats breaking everything (maybe not) laser io or rubidium
