### ISSUE TITLE
Request for rendering assistance

### ISSUE THREAD

**Issue by Natervater** [Direwolf20-MC/LaserIO#224]
### Describe the feature you'd like to have added

First, Fully understand its impossible to account for every issue when Minecraft modding is such a massive scene. I am hoping for help more than reporting an issue. When using BSL shader pack, Laser IO node lasers do not show. Here is an example of with and without. 

No shader:
![image](https://github.com/Direwolf20-MC/LaserIO/assets/54920173/b99dab23-eed4-4353-af26-1fa8c558e110)

With Shader:
![image](https://github.com/Direwolf20-MC/LaserIO/assets/54920173/1d62e42f-9aab-4d98-aede-ab6583c92a66)

I checked with the BSL folks and they said to check for an alternate rendering config, I am not seeing anything in the jar file. Is there any advice on making it work with shaders?

**Comment by markygnlg** [comment]
Since you've no suggestions yet, have you tried google with "BSL shader pack alternate rendering config" search?
There are several videos about configs - I'd start with the ones that show "for low end PCs" as those tend to fix problems like yours.

**Comment by Direwolf20-MC** [comment]
Yea sorry, I have no idea how shaders work or how to support them better :).  Unless someone can give me some direct guidance, I'm just not going to be able to support them.  Maybe if you set the alpha to 255 in the new node rendering settings it'll work?

**Comment by dylithian** [comment]
So I've been doing some research on this because I genuinely can't imagine what setting is even causing this issue. Elsewhere there are people having weird green-light issues, but that's apparently resolvable by disabling bloom, which I've confirmed.

What I've found so far amounts to this:
- Setting the Alpha for the nodes does **not** fix the issue -- it doesn't seem to change regardless of the value, and holding the laser wrench also doesn't fix it
- The actual lasers for interacting with inventories seem to render just fine:
![image](https://github.com/user-attachments/assets/8134bc70-8f40-471b-9bb4-22a5707ed254)
- Disabling shaders does (obviously) fix the issue
- None of the obvious settings in the shader settings seem to fix it. I obviously haven't tried literally all of them, but I also haven't the slightest idea which one could even be causing this.

If I do find something, I'll post it here, but for now it seems like something to do with the way the lasers themselves are rendered is getting turned off by the shaders. Maybe something to do with particles?
