### ISSUE TITLE
NBT filter for 'Enchanted' lets all items through

### ISSUE THREAD

**Issue by radwadas** [Direwolf20-MC/LaserIO#266]
### LaserIO version

1.6.8

### Minecraft Version

1.20.1

### Forge Version

47.2.20

### Modpack & Version

ATM9 to the sky 1.0.5

### Do you have optifine installed?

Yes

### Describe the issue

NBT filter doesn't filter enchanted items properly

### Steps to reproduce

1. Set up 2 chests and 2 nodes
2. Add item extraction card with NBT filter set to deny 'Enchantments' to node 1
3. Add item insert card to node 2
4. Drop some enchanted and unenchanted items to chest 1

Expected:
Only enchanted items are moved

Actual:
All items are moved.

### Expected behaviour

Only unenchanted items are moved

### Screenshots

![image](https://github.com/Direwolf20-MC/LaserIO/assets/853729/fbf62a27-a742-47ea-b45d-158585f81bcb)

### Additional information

I honestly don't know what I could be doing wrong. This seems like a basic function of that filter but is completely ignored.
Is there a way to debug this mod? Like see what the logic was behind it deciding if item in movable?

**Comment by jponeticarvalho** [comment]
I take a look in the code, and seems that the NBT filter is not comparing any tag, because the tags aren`t setted.
during the port to 1.20.6 we have a commit to code be able to compile that removes the setTag functions from NBT filters:
Commit: https://github.com/Direwolf20-MC/LaserIO/commit/b7e2834bdba67888b651818d37bc529071991553#diff-a222e8dde2e48451302bf9b4773e2439ee6c68c05e73d02cf08f2d16ce905dadL54-R90

Maybe one possible fix is try to get a similar implementation from FilterTag 
https://github.com/Direwolf20-MC/LaserIO/blob/main/src/main/java/com/direwolf20/laserio/common/items/filters/FilterTag.java#L76-L82


@Direwolf20-MC  i tested too and seems that the NBT Filter is not working at all with Extract Cards or Insert Cards.

**Comment by Direwolf20-MC** [comment]
Yea I had to disable NBT tags because NBT got removed from items :).  But this bug report is for 1.20.1

**Comment by LokeYourC3PH** [comment]
Funnily enough I was looking for a function for NBT Tags or Mod Tag that lets all items be detected, so that I can use a Sensor Card which checks for if ANY item is present in an inventory at all, not a specific one. Sadly that wasn't a function as it seems, but using this bug actually made me achieve what I was looking for. @Direwolf20-MC would you mind adding an NOR/NAND filter to the Sensor card so that we can make it output a signal if no item is defined/present? That way I needn't rely on a bug :)

**Comment by Direwolf20-MC** [comment]
I'll see what I can do, i'll work on something once I get the NBT filter back

**Comment by Direwolf20-MC** [comment]
Found the bug and it should be fixed going forward on the new Data Filter :)

**Comment by DoomSquirter** [comment]
just to be clear.  1.20.1 is not going to get the nbt filter card fixed?
