### ISSUE TITLE
add filters to the "card holder" allowed items?

### ISSUE THREAD

**Issue by IncandescentCore** [Direwolf20-MC/LaserIO#35]
### Describe the feature you'd like to have added

filter cards storage.

### Additional information

Personally i'd like to be able to put the filters in with the "cards" in the card holder,

**Comment by Direwolf20-MC** [comment]
For now I'm going to say no -- mostly because I don't want to add the card holder UI to the Card UIs. I can allow you to put the filters in the holder, but then they wouldn't be easily accessible to cards. So I'm just gonna hold off for now - since they stack it shouldn't be that hard to keep track of it.
