### ISSUE TITLE
Feature more ez side config

### ISSUE THREAD

**Issue by castilio20** [Direwolf20-MC/LaserIO#37]
### Describe the feature you'd like to have added

right now with east west side is a little les intiutive and you have to gues a little
would be nice if would be more ez like color for each side that mach to the tabs
or somthing more ez to know
the node doesnt  have distinct faces

**Comment by aethaerya** [comment]
I also think QoL could be improved a little with configuring each side, because as it is now, the average player must do one of the following:
1. F3
2. Trace the stars like our ancestors/Install a compass type mod
3. The guessing game
4. Walk inside blocks/break blocks & re-place them after inserting a card or filter.

There are a few things that I wish to suggest:
1. When inserting a card/filter, automatically insert into the face with an adjacent inventory block, regardless of the side the player clicks. In the case of a node with multiple adjacent inventories see next suggestion.
2. Show the item texture of an adjacent inventory block somewhere around the respective tab of each face, if any. I think the directional labels are still important, especially for repeating inventory types.
3. The ability to change the a node's frame or its faces' colors, and have the direction tabs colored accordingly?

**Comment by Remixed-Witch** [comment]
Holding the Laser Wrench could display a colour overlay for each side when you are looking at a node.

Also if you are to take this suggestion, I would also say please would you pay homage to buildcraft and match the colours and orientation to the same as the diamond pipe's.

**Comment by SanderElsen** [comment]
I was looking into this for myself and made a variation that displays the neighboring block's name instead of the direction on the node screen. (Example below)
My next step would be to display a small icon of the block inside the tab.

Is that something that could help the general public?
I'm very new to modding so just let me know if I'm off the mark.

related commit: https://github.com/SanderElsen/LaserIO/commit/5058d214c2924e6455a36a80037f17c35b8bc906

<details>
<summary>Example</summary>

![north](https://user-images.githubusercontent.com/8928650/183298633-ee8891c3-e151-4d3a-97b3-2d27d0127caa.png)
![south](https://user-images.githubusercontent.com/8928650/183298636-3cfb7449-0bc6-4cba-bf14-f519c9d3f937.png)


</details>

**Comment by SanderElsen** [comment]
Update: The variant with the blocks inside the tabs, I think I'm going to keep this one active for myself as it has the benefit of not having to check each tab and hovering the block also shows the block's tooltip incase I get confused what each block is.

The code is sketchy at best but works for me and as a POC

related commit: https://github.com/SanderElsen/LaserIO/commit/942b029bae4a2d76e56dfc8eaa9b269d108ca69d

<details>
<summary>Details</summary>

![west](https://user-images.githubusercontent.com/8928650/183436570-462a4efa-9a25-4c06-81a7-deb76f198c63.png)
![east](https://user-images.githubusercontent.com/8928650/183436576-a7157e2f-c3ed-419c-9ba5-767e43465787.png)


</details>

**Comment by Direwolf20-MC** [comment]
Added to a features wishlist i'm keeping
