### ISSUE TITLE
card holder to support filters

### ISSUE THREAD

**Issue by redgoblin88** [Direwolf20-MC/LaserIO#40]
### Describe the feature you'd like to have added

now we have card holders to support the different cars that determine the extraction/insertion type (fluid, item, energy, redstone e.c.t.) how about the ability to put in the different kinds of filters into the card holder, to help keep the player inventory organised as well as having all the node configuration you may need in the holder

**Comment by Direwolf20-MC** [comment]
For now I'm going to say no -- mostly because I don't want to add the card holder UI to the Card UIs. I can allow you to put the filters in the holder, but then they wouldn't be easily accessible to cards. So I'm just gonna hold off for now - since they stack it shouldn't be that hard to keep track of it.
