### ISSUE TITLE
Ability to copy a card

### ISSUE THREAD

**Issue by ralmeida** [Direwolf20-MC/LaserIO#46]
### Describe the feature you'd like to have added

When setting up a large system that would say need 10 extractor cards set to orange it would be super easy if we could craft:

1 Configured Card 
1 Other Card (set to defaults)
-----
Output:
- 1 Configured Card (original) 
- 1 'Copy' of the Configured Card

**Comment by alecium** [comment]
This already sort of exists.  If you have a stack of the 10 cards in your Card Holder and right click the stack, you can configure them all at one time.  Not exactly the same as the title implies which is more for the ability to copy an existing card (which would be nice), but the existing "mass-configuring" feature would help out when you "need 10 extractor cards set to orange" like you described.

**Comment by Direwolf20-MC** [comment]
Correct you can bulk modify cards inside the card holder.

**Comment by CyberFoxar** [comment]
You can bulk modify, but not bulk-overdrive or bulk-add-filter, even provided you have all the materials.

If I need 12 energy cards set to extract with one overclock so it can extract 4k FE/t... I need to configure each one manually. I can bulk set them to extract, but not bulk add the overclocker.

Related to #158

**Comment by credomane** [comment]
Yeah I would really love a way to copy-n-paste the settings (NOT connections) of one entire node to another or even just the face of one node to a different face of the same node or another node.

- Node overclock cards in each face of the node.
- Cards in each face of the node
  - Config of each card.
    - Including filters and the filter's settings.
    - Overclocks in each card.

The node to node/connectors is quickest part of any LaserIO setup I do. Having to setup dozens of nodes with the exact same setup over and over really slows things down and is sadly, for me, quite error prone.

On paste have it check player's inventory and card holder for the needed cards/overclocks/filters and then depending on if the needed number is met either perform the paste or spit out an error of missing required items. A partial paste would be bad so all or nothing, imo.

I'd leave the connection settings of the node to other nodes/connectors out though and leave that as manual only. Otherwise that could turn into a rat's nest and/or connect laserio "networks" that are meant to be separate but otherwise functionally have the same setup.
