### ISSUE TITLE
LaserIO interaction with Apotheosis Spawner

### ISSUE THREAD

**Issue by Kaylasangle** [Direwolf20-MC/LaserIO#96]
### LaserIO version

1.3.1

### Minecraft Version

1.18.2

### Forge Version

40.1.60

### Modpack & Version

TNP Limitless 5

### Do you have optifine installed?

No

### Describe the issue

Apotheosis spawner does not LOOK active when a redstone signal is present with the node

### Steps to reproduce

get an apotheosis spawner, right click it with comparator then place a node on top with redstone card then give it a signal through the node to power the spawner

### Expected behaviour

the spawner does not look active even though it is active

**Comment by Direwolf20-MC** [comment]
Try with the latest version of the mod.  Also, does placing a block next to the spawner make it start looking active?  It might be a bug with Apotheosis, but i'm not sure.

**Comment by zortag** [comment]
In All the Mods 9 modpack (MC 1.20.1, Laser IO 1.6.8) the issue is still present.
The output laser change intensity, proving the link works, but the spawner (it works correct with levers or redstone dust) not be activated. Placing a redstone dust as interface it works. IDK if the issue is caused by Laser IO or Apotheosis
